research_task:
  description: Use vector search to research the topic "{topic}" and find relevant context.
  expected_output: A list of 3–5 detailed insights about the topic.
  agent: research_agent

answer_task:
  description: Using the research, generate a clear and informative answer about {topic},
    If the input contains "No relevant information found for your query.", 
    simply return the same message and do not generate anything.
  agent: answer_agent
  expected_output: A final, coherent answer suitable for end users or fallback message.

  
 
